/*!
 * SAP UI development toolkit for HTML5 (SAPUI5) (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.suite.ui.commons.HeaderContainer");jQuery.sap.require("sap.suite.ui.commons.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.suite.ui.commons.HeaderContainer",{metadata:{interfaces:["sap.m.ObjectHeaderContainer"],library:"sap.suite.ui.commons",properties:{"scrollStep":{type:"int",group:"Misc",defaultValue:300},"scrollTime":{type:"int",group:"Misc",defaultValue:500},"showDividers":{type:"boolean",group:"Misc",defaultValue:true},"view":{type:"sap.suite.ui.commons.HeaderContainerView",group:"Misc",defaultValue:sap.suite.ui.commons.HeaderContainerView.Horizontal},"height":{type:"sap.ui.core.CSSSize",group:"Misc",defaultValue:null}},aggregations:{"scrollContainer":{type:"sap.ui.core.Control",multiple:false,visibility:"hidden"},"items":{type:"sap.ui.core.Control",multiple:true,singularName:"item"},"buttonPrev":{type:"sap.ui.core.Control",multiple:false,visibility:"hidden"},"buttonNext":{type:"sap.ui.core.Control",multiple:false,visibility:"hidden"}}}});jQuery.sap.require("sap.ui.core.IconPool");jQuery.sap.require("sap.ui.core.Icon");jQuery.sap.require("sap.ui.core.delegate.ItemNavigation");
sap.suite.ui.commons.HeaderContainer.prototype.init=function(){this._bRtl=sap.ui.getCore().getConfiguration().getRTL();this._rb=sap.ui.getCore().getLibraryResourceBundle("sap.suite.ui.commons");this._oScrollCntr=new sap.m.ScrollContainer(this.getId()+"-scrl-cntnr",{width:"100%",horizontal:!jQuery.device.is.desktop,height:"100%"});this.setAggregation("scrollContainer",this._oScrollCntr);var t=this;var w=0;sap.ui.Device.resize.attachHandler(function(o){if(w!=o.width){w=o.width;}});if(jQuery.device.is.desktop){this._oArrowPrev=new sap.m.Button({id:this.getId()+"-scrl-prev-button",type:sap.m.ButtonType.Transparent,tooltip:this._rb.getText("HEADERCONTAINER_BUTTON_PREV_SECTION"),press:function(e){t._scroll(-t.getScrollStep(),t.getScrollTime());}});this._oArrowPrev.addStyleClass("sapSuiteHdrCntrBtn").addStyleClass("sapSuiteHdrCntrLeft");this.setAggregation("buttonPrev",this._oArrowPrev);this._oArrowNext=new sap.m.Button({id:this.getId()+"-scrl-next-button",type:sap.m.ButtonType.Transparent,tooltip:this._rb.getText("HEADERCONTAINER_BUTTON_NEXT_SECTION"),press:function(e){t._scroll(t.getScrollStep(),t.getScrollTime());}});this._oArrowNext.addStyleClass("sapSuiteHdrCntrBtn").addStyleClass("sapSuiteHdrCntrRight");this.setAggregation("buttonNext",this._oArrowNext);this._oScrollCntr.addDelegate({onAfterRendering:function(o){if(jQuery.device.is.desktop){var f=jQuery.sap.domById(t.getId()+"-scrl-cntnr-scroll");var F=jQuery.sap.byId(t.getId()+"-scrl-cntnr-scroll");var d=F.find("[tabindex=0]");if(!t._oItemNavigation){t._oItemNavigation=new sap.ui.core.delegate.ItemNavigation();t.addDelegate(t._oItemNavigation);t._oItemNavigation.attachEvent(sap.ui.core.delegate.ItemNavigation.Events.BorderReached,t._handleBorderReached,t);t._oItemNavigation.attachEvent(sap.ui.core.delegate.ItemNavigation.Events.AfterFocus,t._handleBorderReached,t);}t._oItemNavigation.setRootDomRef(f);t._oItemNavigation.setItemDomRefs(d);t._oItemNavigation.setCycling(false);}},onBeforeRendering:function(o){if(jQuery.device.is.desktop){jQuery.sap.require("sap.ui.core.delegate.ScrollEnablement");t._oScrollCntr._oScroller=new sap.ui.core.delegate.ScrollEnablement(t._oScrollCntr,t._oScrollCntr.getId()+"-scroll",{horizontal:true,vertical:true,zynga:false,preventDefault:false,nonTouchScrolling:true});}}});}};
sap.suite.ui.commons.HeaderContainer.prototype._scroll=function(d,D){this.bScrollInProcess=true;var t=this;setTimeout(function(){t.bScrollInProcess=false;},D+300);if(this.getView()=="Horizontal"){this._hScroll(d,D);}else{this._vScroll(d,D);}};
sap.suite.ui.commons.HeaderContainer.prototype._vScroll=function(d,D){var o=jQuery.sap.domById(this.getId()+"-scrl-cntnr");var s=o.scrollTop;var S=s+d;this._oScrollCntr.scrollTo(0,S,D);};
sap.suite.ui.commons.HeaderContainer.prototype._hScroll=function(d,D){var o=jQuery.sap.domById(this.getId()+"-scrl-cntnr");if(!this._bRtl){var s=o.scrollLeft;var S=s+d;this._oScrollCntr.scrollTo(S,0,D);}else{var S=jQuery(o).scrollRightRTL()+d;this._oScrollCntr.scrollTo((S>0)?S:0,0,D);}};
sap.suite.ui.commons.HeaderContainer.prototype._checkOverflow=function(){if(this.getView()=="Horizontal"){this._checkHOverflow();}else{this._checkVOverflow();}};
sap.suite.ui.commons.HeaderContainer.prototype._checkVOverflow=function(){var b=jQuery.sap.domById(this.getId()+"-scrl-cntnr");var s=false;if(b){if(b.scrollHeight>b.clientHeight){s=true;}}this._lastVScrolling=s;if(b){var S=b.scrollTop;var a=false;var c=false;var r=b.scrollHeight;var d=b.clientHeight;if(Math.abs(r-d)==1){r=d;}if(S>0){a=true;}if((r>d)&&(S+d+32<r)){c=true;}var o=jQuery.sap.byId(this.getId()+"-scroll-area");if(!a){jQuery.sap.byId(this._oArrowPrev.getId()).hide();o.css("padding-top","0px");}else{jQuery.sap.byId(this._oArrowPrev.getId()).show();o.css("padding-top","32px");}if(!c){jQuery.sap.byId(this._oArrowNext.getId()).hide();o.css("padding-bottom","0px");}else{jQuery.sap.byId(this._oArrowNext.getId()).show();o.css("padding-bottom","32px");}}};
sap.suite.ui.commons.HeaderContainer.prototype._checkHOverflow=function(){var b=jQuery.sap.domById(this.getId()+"-scrl-cntnr");var B=jQuery.sap.byId(this.getId()+"-scroll-area");var s=false;if(b){if(b.scrollWidth>b.clientWidth){s=true;}}this._lastScrolling=s;if(b){var S=b.scrollLeft;var a=false;var c=false;var r=b.scrollWidth;var d=b.clientWidth;if(Math.abs(r-d)==1){r=d;}if(this._bRtl){var i=jQuery(b).scrollLeftRTL();if(i>(sap.ui.Device.browser.internet_explorer?1:0)){c=true;}}else{if(S>0){a=true;}}var R=function(){var p=parseFloat(B.css("padding-right"));return sap.ui.Device.browser.internet_explorer?p+1:p;};if(r>d){if(this._bRtl){if(jQuery(b).scrollRightRTL()>0){a=true;}}else{if(Math.abs(S+d-r)>R()){c=true;}}}var o=jQuery.sap.byId(this.getId()+"-scroll-area");var O=this._oArrowPrev.$().is(":visible");var e=this._oScrollCntr.getScrollDelegate();var f=false;if(O&&!a){jQuery.sap.byId(this._oArrowPrev.getId()).hide();o.css(this._bRtl?"padding-right":"padding-left","0rem");f=true;}if(!O&&a){jQuery.sap.byId(this._oArrowPrev.getId()).show();o.css(this._bRtl?"padding-right":"padding-left","2rem");f=true;}var g=this._oArrowNext.$().is(":visible");if(g&&!c){jQuery.sap.byId(this._oArrowNext.getId()).hide();o.css(this._bRtl?"padding-left":"padding-right","0rem");f=true;}if(!g&&c){jQuery.sap.byId(this._oArrowNext.getId()).show();o.css(this._bRtl?"padding-left":"padding-right","2rem");f=true;}if(f){this._refreshScroll();}}};
sap.suite.ui.commons.HeaderContainer.prototype._handleBorderReached=function(o){var i=o.getParameter("index");if(i==0){this._scroll(-this.getScrollStep(),this.getScrollTime());}else if(i==this.getItems().length-1){this._scroll(this.getScrollStep(),this.getScrollTime());}};
sap.suite.ui.commons.HeaderContainer.prototype.addItem=function(i,s){var r=this._oScrollCntr.addContent(i.addStyleClass("sapSuiteHrdrCntrInner"),s);return r;};
sap.suite.ui.commons.HeaderContainer.prototype.insertItem=function(i,I,s){var r=this._oScrollCntr.insertContent(i.addStyleClass("sapSuiteHrdrCntrInner"),I,s);return r;};
sap.suite.ui.commons.HeaderContainer.prototype._callMethodInManagedObject=function(f,a){var t=this;var b=Array.prototype.slice.call(arguments);if(a==="items"){b[1]="content";return this._oScrollCntr[f].apply(this._oScrollCntr,b.slice(1));}else{return sap.ui.base.ManagedObject.prototype[f].apply(this,b.slice(1));}};
sap.suite.ui.commons.HeaderContainer.prototype.onBeforeRendering=function(){if(jQuery.device.is.desktop){sap.ui.getCore().attachIntervalTimer(this._checkOverflow,this);this._oArrowPrev.setIcon(this.getView()=="Horizontal"?"sap-icon://navigation-left-arrow":"sap-icon://navigation-up-arrow");this._oArrowNext.setIcon(this.getView()=="Horizontal"?"sap-icon://navigation-right-arrow":"sap-icon://navigation-down-arrow");this.$().unbind("click",this.handleSwipe);}};
sap.suite.ui.commons.HeaderContainer.prototype.onAfterRendering=function(){jQuery.sap.byId(this.getId()+"-scrl-next-button").attr("tabindex","-1");jQuery.sap.byId(this.getId()+"-scrl-prev-button").attr("tabindex","-1");if(jQuery.device.is.desktop){this.$().bind("swipe",jQuery.proxy(this.handleSwipe,this));}if(this._sScrollResizeHandlerId){sap.ui.core.ResizeHandler.deregister(this._sScrollResizeHandlerId);}var s=jQuery.sap.domById(this.getId()+"-scrl-cntnr");};
sap.suite.ui.commons.HeaderContainer.prototype._refreshScroll=function(){if(!this.bScrollInProcess){this._oScrollCntr.getScrollDelegate().refresh();}};
sap.suite.ui.commons.HeaderContainer.prototype.handleSwipe=function(e){e.preventDefault();e.stopPropagation();this._isDragEvent=true;};
sap.suite.ui.commons.HeaderContainer.prototype.exit=function(){if(this._oItemNavigation){this.removeDelegate(this._oItemNavigation);this._oItemNavigation.destroy();}};
sap.suite.ui.commons.HeaderContainer.prototype.onclick=function(e){if(this._isDragEvent){e.preventDefault();e.stopPropagation();this._isDragEvent=false;}};
sap.suite.ui.commons.HeaderContainer.prototype.setView=function(o){this.setProperty("view",o);if(o==sap.suite.ui.commons.HeaderContainerView.Horizontal&&!jQuery.device.is.desktop){this._oScrollCntr.setHorizontal(true);this._oScrollCntr.setVertical(false);}else if(!jQuery.device.is.desktop){this._oScrollCntr.setHorizontal(false);this._oScrollCntr.setVertical(true);}return this;};
sap.suite.ui.commons.HeaderContainer.prototype.validateAggregation=function(a,o,m){return this._callMethodInManagedObject("validateAggregation",a,o,m);};
sap.suite.ui.commons.HeaderContainer.prototype.getAggregation=function(a,o,s){return this._callMethodInManagedObject("getAggregation",a,o,s);};
sap.suite.ui.commons.HeaderContainer.prototype.setAggregation=function(a,o,s){this._callMethodInManagedObject("setAggregation",a,o,s);return this;};
sap.suite.ui.commons.HeaderContainer.prototype.indexOfAggregation=function(a,o){return this._callMethodInManagedObject("indexOfAggregation",a,o);};
sap.suite.ui.commons.HeaderContainer.prototype.insertAggregation=function(a,o,i,s){this._callMethodInManagedObject("insertAggregation",a,o,i,s);return this;};
sap.suite.ui.commons.HeaderContainer.prototype.addAggregation=function(a,o,s){this._callMethodInManagedObject("addAggregation",a,o,s);return this;};
sap.suite.ui.commons.HeaderContainer.prototype.removeAggregation=function(a,o,s){return this._callMethodInManagedObject("removeAggregation",a,o,s);};
sap.suite.ui.commons.HeaderContainer.prototype.removeAllAggregation=function(a,s){return this._callMethodInManagedObject("removeAllAggregation",a,s);};
sap.suite.ui.commons.HeaderContainer.prototype.destroyAggregation=function(a,s){this._callMethodInManagedObject("destroyAggregation",a,s);return this;};
