/*!
 * SAP UI development toolkit for HTML5 (SAPUI5) (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.suite.ui.commons.MicroAreaChart");jQuery.sap.require("sap.suite.ui.commons.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.suite.ui.commons.MicroAreaChart",{metadata:{library:"sap.suite.ui.commons",properties:{"width":{type:"sap.ui.core.CSSSize",group:"Misc",defaultValue:'200px'},"height":{type:"sap.ui.core.CSSSize",group:"Misc",defaultValue:'190px'},"maxXValue":{type:"float",group:"Misc",defaultValue:null},"minXValue":{type:"float",group:"Misc",defaultValue:null},"maxYValue":{type:"float",group:"Misc",defaultValue:null},"minYValue":{type:"float",group:"Misc",defaultValue:null},"view":{type:"sap.suite.ui.commons.MicroAreaChartView",group:"Appearance",defaultValue:sap.suite.ui.commons.MicroAreaChartView.Normal}},aggregations:{"chart":{type:"sap.suite.ui.commons.MicroAreaChartItem",multiple:false},"maxThreshold":{type:"sap.suite.ui.commons.MicroAreaChartItem",multiple:false},"innerMaxThreshold":{type:"sap.suite.ui.commons.MicroAreaChartItem",multiple:false},"innerMinThreshold":{type:"sap.suite.ui.commons.MicroAreaChartItem",multiple:false},"minThreshold":{type:"sap.suite.ui.commons.MicroAreaChartItem",multiple:false},"target":{type:"sap.suite.ui.commons.MicroAreaChartItem",multiple:false},"firstXLabel":{type:"sap.suite.ui.commons.MicroAreaChartLabel",multiple:false},"firstYLabel":{type:"sap.suite.ui.commons.MicroAreaChartLabel",multiple:false},"lastXLabel":{type:"sap.suite.ui.commons.MicroAreaChartLabel",multiple:false},"lastYLabel":{type:"sap.suite.ui.commons.MicroAreaChartLabel",multiple:false},"maxLabel":{type:"sap.suite.ui.commons.MicroAreaChartLabel",multiple:false},"minLabel":{type:"sap.suite.ui.commons.MicroAreaChartLabel",multiple:false}},events:{"press":{}}}});sap.suite.ui.commons.MicroAreaChart.M_EVENTS={'press':'press'};
sap.suite.ui.commons.MicroAreaChart.prototype.init=function(){this._oRb=sap.ui.getCore().getLibraryResourceBundle("sap.suite.ui.commons");this.setTooltip("{AltText}");};
sap.suite.ui.commons.MicroAreaChart.prototype._getCssValues=function(){this._cssHelper.className=Array.prototype.slice.call(arguments).join(" ");var c=window.getComputedStyle(this._cssHelper);if(c.backgroundColor==undefined){c.backgroundColor=c["background-color"];}if(c.outlineStyle==undefined){c.outlineStyle=c["outline-style"];}if(c.outlineWidth==undefined){c.outlineWidth=c["outline-width"];}return c;};
sap.suite.ui.commons.MicroAreaChart.prototype._fillThresholdArea=function(c,p,P,a){c.beginPath();c.moveTo(p[0].x,p[0].y);for(var i=1,l=p.length;i<l;i++){c.lineTo(p[i].x,p[i].y);}for(var i=P.length-1;i>=0;i--){c.lineTo(P[i].x,P[i].y);}c.closePath();c.fillStyle="white";c.fill();c.fillStyle=a;c.fill();c.lineWidth=1;c.strokeStyle="white";c.stroke();c.strokeStyle=a;c.stroke();};
sap.suite.ui.commons.MicroAreaChart.prototype._renderDashedLine=function(c,p,d,D){if(c.setLineDash){c.setLineDash(D);this._renderLine(c,p,d);c.setLineDash([]);}else{c.beginPath();for(var i=0,l=p.length-1;i<l;i++){c._dashedLine(p[i].x,p[i].y,p[i+1].x,p[i+1].y,D);}c.stroke();}};
sap.suite.ui.commons.MicroAreaChart.prototype._renderLine=function(c,p,d){c.beginPath();c.moveTo(p[0].x,p[0].y);for(var i=1,l=p.length;i<l;i++){c.lineTo(p[i].x,p[i].y);}c.stroke();};
sap.suite.ui.commons.MicroAreaChart.prototype.renderTarget=function(c,d){if(d.target.length>1){var C=this._getCssValues("sapSuiteMacTarget",this.getTarget().getColor());c.strokeStyle=C.color;c.lineWidth=parseFloat(C.width);if(C.outlineStyle=="dotted"){this._renderDashedLine(c,d.target,d,[parseFloat(C.outlineWidth),3]);}else{this._renderLine(c,d.target,d);}}else if(d.target.length==1){jQuery.sap.log.warning("Target is not rendered because only 1 point was given");}};
sap.suite.ui.commons.MicroAreaChart.prototype.renderThresholdLine=function(c,p,d){if(p&&p.length){var C=this._getCssValues("sapSuiteMacThreshold");c.strokeStyle=C.color;c.lineWidth=C.width;this._renderLine(c,p,d);}};
sap.suite.ui.commons.MicroAreaChart.prototype.fillMaxThreshold=function(c,d){if(d.maxThreshold.length>1){var C=this._getCssValues("sapSuiteMacThreshold",this.getMaxThreshold().getColor());this._fillThresholdArea(c,d.maxThreshold,[{x:d.maxThreshold[0].x,y:d.minY},{x:d.maxThreshold[d.maxThreshold.length-1].x,y:d.minY}],C.backgroundColor);this.renderThresholdLine(c,d.maxThreshold,d);}else if(d.maxThreshold.length==1){jQuery.sap.log.warning("Max Threshold is not rendered because only 1 point was given");}};
sap.suite.ui.commons.MicroAreaChart.prototype.fillMinThreshold=function(c,d){if(d.minThreshold.length>1){var C=this._getCssValues("sapSuiteMacThreshold",this.getMinThreshold().getColor());this._fillThresholdArea(c,d.minThreshold,[{x:d.minThreshold[0].x,y:d.maxY},{x:d.minThreshold[d.minThreshold.length-1].x,y:d.maxY}],C.backgroundColor);}else if(d.minThreshold.length==1){jQuery.sap.log.warning("Min Threshold is not rendered because only 1 point was given");}};
sap.suite.ui.commons.MicroAreaChart.prototype.fillThresholdArea=function(c,d){if(d.minThreshold.length>1&&d.maxThreshold.length>1){var C=this._getCssValues("sapSuiteMacThreshold","Critical");this._fillThresholdArea(c,d.maxThreshold,d.minThreshold,C.backgroundColor);}};
sap.suite.ui.commons.MicroAreaChart.prototype.fillInnerThresholdArea=function(c,d){if(d.innerMinThreshold.length>1&&d.innerMaxThreshold.length>1){var C=this._getCssValues("sapSuiteMacThreshold",this.getInnerMaxThreshold().getColor());this._fillThresholdArea(c,d.innerMaxThreshold,d.innerMinThreshold,C.backgroundColor);}else if(d.innerMinThreshold.length||d.innerMaxThreshold.length){jQuery.sap.log.warning("Inner threshold area is not rendered because inner min and max threshold were not correctly set");}};
sap.suite.ui.commons.MicroAreaChart.prototype.renderChart=function(c,d){if(d.chart.length>1){var C=this._getCssValues("sapSuiteMacChart",this.getChart().getColor());c.strokeStyle=C.color;c.lineWidth=parseFloat(C.width);this._renderLine(c,d.chart,d);}else if(d.chart.length==1){jQuery.sap.log.warning("Actual values are not rendered because only 1 point was given");}};
sap.suite.ui.commons.MicroAreaChart.prototype.renderCanvas=function(){this._cssHelper=document.getElementById(this.getId()+"-css-helper");var l=this.$().find(".sapSuiteMacSideLabels").css("width");this.$().find(".sapSuiteMacCanvas, .sapSuiteMacLabels").css("right",l).css("left",l);var a=document.getElementById(this.getId()+"-canvas");var b=window.getComputedStyle(a);var w=parseFloat(b.width);a.setAttribute("width",w?w:360);var h=parseFloat(b.height);a.setAttribute("height",h?h:242);var c=a.getContext("2d");c.lineJoin="round";c._dashedLine=function(x,y,e,f,g){var i=g.length;this.moveTo(x,y);var j=(e-x),k=(f-y);var s=j?k/j:1e15;var m=Math.sqrt(j*j+k*k);var n=0,o=true;while(m>=0.1){var p=g[n++%i];if(p>m){p=m;}var q=Math.sqrt(p*p/(1+s*s));if(j<0){q=-q;}x+=q;y+=s*q;this[o?'lineTo':'moveTo'](x,y);m-=p;o=!o;}};var d=this._calculateDimensions(a.width,a.height);this.fillMaxThreshold(c,d);this.fillMinThreshold(c,d);this.fillThresholdArea(c,d);this.renderThresholdLine(c,d.minThreshold,d);this.renderThresholdLine(c,d.maxThreshold,d);this.fillInnerThresholdArea(c,d);this.renderThresholdLine(c,d.innerMinThreshold,d);this.renderThresholdLine(c,d.innerMaxThreshold,d);this.renderTarget(c,d);this.renderChart(c,d);};
sap.suite.ui.commons.MicroAreaChart.prototype._calculateDimensions=function(w,h){var m,b,c,d;m=b=c=d=undefined;var t=this;function e(){if(!t._isMinXValue||!t._isMaxXValue||!t._isMinYValue||!t._isMaxYValue){var l=[];if(t.getMaxThreshold()){l.push(t.getMaxThreshold());}if(t.getMinThreshold()){l.push(t.getMinThreshold());}if(t.getChart()){l.push(t.getChart());}if(t.getTarget()){l.push(t.getTarget());}if(t.getInnerMaxThreshold()){l.push(t.getInnerMaxThreshold());}if(t.getInnerMinThreshold()){l.push(t.getInnerMinThreshold());}for(var i=0,n=l.length;i<n;i++){var p=l[i].getPoints();for(var o=0,a=p.length;o<a;o++){var q=p[o].getXValue();if(q>m||m===undefined){m=q;}if(q<c||c===undefined){c=q;}q=p[o].getYValue();if(q>b||b===undefined){b=q;}if(q<d||d===undefined){d=q;}}}}if(t._isMinXValue){c=t.getMinXValue();}if(t._isMaxXValue){m=t.getMaxXValue();}if(t._isMinYValue){d=t.getMinYValue();}if(t._isMaxYValue){b=t.getMaxYValue();}};e();var r={minY:0,minX:0,maxY:h,maxX:w};var k=undefined;var D=m-c;if(D>0){k=w/D;}else if(D==0){k=0;r.maxX/=2;}else{jQuery.sap.log.warning("Min X is more than max X");}var f=undefined;var g=b-d;if(g>0){f=h/(b-d);}else if(g==0){f=0;r.maxY/=2;}else{jQuery.sap.log.warning("Min Y is more than max Y");}function j(l){var R=sap.ui.getCore().getConfiguration().getRTL();var C=function(V){var x=k*(V-c);if(R){x=r.maxX-x;}return x;};var a=function(V){return r.maxY-f*(V-d);};var n=[];if(l&&k!=undefined&&f!=undefined){var p=l.getPoints();var L=p.length;var o,y,q,s;if(L==1){q=p[0].getXValue();s=p[0].getYValue();if(q==undefined^s==undefined){var u,v;if(q==undefined){v=y=a(s);o=r.minX;u=r.maxX;}else{u=o=C(q);y=r.minY;v=r.maxY;}n.push({x:o,y:y},{x:u,y:v});}else{jQuery.sap.log.warning("Point with coordinates ["+q+" "+s+"] ignored");}}else{for(var i=0;i<L;i++){q=p[i].getXValue();s=p[i].getYValue();if(q!=undefined&&s!=undefined){o=C(q);y=a(s);n.push({x:o,y:y});}else{jQuery.sap.log.warning("Point with coordinates ["+q+" "+s+"] ignored");}}}}return n;};r.maxThreshold=j(t.getMaxThreshold());r.minThreshold=j(t.getMinThreshold());r.chart=j(t.getChart());r.target=j(t.getTarget());r.innerMaxThreshold=j(t.getInnerMaxThreshold());r.innerMinThreshold=j(t.getInnerMinThreshold());return r;};
sap.suite.ui.commons.MicroAreaChart.prototype.setMinXValue=function(v,s){this._isMinXValue=this._isNumber(v);return this.setProperty("minXValue",this._isMinXValue?v:NaN,s);};
sap.suite.ui.commons.MicroAreaChart.prototype.setMaxXValue=function(v,s){this._isMaxXValue=this._isNumber(v);return this.setProperty("maxXValue",this._isMaxXValue?v:NaN,s);};
sap.suite.ui.commons.MicroAreaChart.prototype.setMinYValue=function(v,s){this._isMinYValue=this._isNumber(v);return this.setProperty("minYValue",this._isMinYValue?v:NaN,s);};
sap.suite.ui.commons.MicroAreaChart.prototype.setMaxYValue=function(v,s){this._isMaxYValue=this._isNumber(v);return this.setProperty("maxYValue",this._isMaxYValue?v:NaN,s);};
sap.suite.ui.commons.MicroAreaChart.prototype._isNumber=function(n){return typeof n=='number'&&!isNaN(n)&&isFinite(n);};
sap.suite.ui.commons.MicroAreaChart.prototype.onAfterRendering=function(){this.renderCanvas();};
sap.suite.ui.commons.MicroAreaChart.prototype.ontap=function(e){if(sap.ui.Device.browser.internet_explorer){this.$().focus();}this.firePress();};
sap.suite.ui.commons.MicroAreaChart.prototype.onkeydown=function(e){if(e.which==jQuery.sap.KeyCodes.SPACE){e.preventDefault();}};
sap.suite.ui.commons.MicroAreaChart.prototype.onkeyup=function(e){if(e.which==jQuery.sap.KeyCodes.ENTER||e.which==jQuery.sap.KeyCodes.SPACE){this.firePress();e.preventDefault();}};
sap.suite.ui.commons.MicroAreaChart.prototype.attachEvent=function(e,d,f,l){sap.ui.core.Control.prototype.attachEvent.call(this,e,d,f,l);if(this.hasListeners("press")){this.$().attr("tabindex",0).addClass("sapSuiteUiCommonsPointer");}return this;};
sap.suite.ui.commons.MicroAreaChart.prototype.detachEvent=function(e,f,l){sap.ui.core.Control.prototype.detachEvent.call(this,e,f,l);if(!this.hasListeners("press")){this.$().removeAttr("tabindex").removeClass("sapSuiteUiCommonsPointer");}return this;};
sap.suite.ui.commons.MicroAreaChart.prototype.getLocalizedColorMeaning=function(c){return this._oRb.getText(("SEMANTIC_COLOR_"+c).toUpperCase());};
sap.suite.ui.commons.MicroAreaChart.prototype.getAltText=function(){var a="";var f=this.getFirstXLabel();var F=this.getFirstYLabel();var l=this.getLastXLabel();var L=this.getLastYLabel();var m=this.getMinLabel();var M=this.getMaxLabel();var A=this.getChart();var t=this.getTarget();var I=true;if(f&&f.getLabel()||F&&F.getLabel()){a+=(I?"":"\n")+this._oRb.getText(("MICRO_AREA_CHART_START"))+": "+f.getLabel()+" "+F.getLabel()+" "+this.getLocalizedColorMeaning(F.getColor());I=false;}if(l&&l.getLabel()||L&&L.getLabel()){a+=(I?"":"\n")+this._oRb.getText(("MICRO_AREA_CHART_END"))+": "+l.getLabel()+" "+L.getLabel()+" "+this.getLocalizedColorMeaning(L.getColor());I=false;}if(m&&m.getLabel()){a+=(I?"":"\n")+this._oRb.getText(("MICRO_AREA_CHART_MINIMAL_VALUE"))+": "+m.getLabel()+" "+this.getLocalizedColorMeaning(m.getColor());I=false;}if(M&&M.getLabel()){a+=(I?"":"\n")+this._oRb.getText(("MICRO_AREA_CHART_MAXIMAL_VALUE"))+": "+M.getLabel()+" "+this.getLocalizedColorMeaning(M.getColor());I=false;}if(A&&A.getPoints()){a+=(I?"":"\n")+this._oRb.getText(("MICRO_AREA_CHART_ACTUAL_VALUES"))+":";I=false;var b=A.getPoints();for(var i=0;i<b.length;i++){a+=" "+b[i].getY();}}if(t&&t.getPoints()){a+=(I?"":"\n")+this._oRb.getText(("MICRO_AREA_CHART_TARGET_VALUES"))+":";var T=t.getPoints();for(var i=0;i<T.length;i++){a+=" "+T[i].getY();}}return a;};
sap.suite.ui.commons.MicroAreaChart.prototype.getTooltip_AsString=function(){var t=this.getTooltip();var T=this.getAltText();if(typeof t==="string"||t instanceof String){T=t.split("{AltText}").join(T);return T;}return t?t:"";};
