/*!
 * SAP UI development toolkit for HTML5 (SAPUI5) (c) Copyright 2009-2013 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.suite.ui.commons.TimelineRenderer");sap.suite.ui.commons.TimelineRenderer={};
sap.suite.ui.commons.TimelineRenderer.render=function(r,c){if(!c.getVisible()){return;}if(c.getAxisOrientation()===sap.suite.ui.commons.TimelineAxisOrientation.Horizontal){this.renderH(r,c);}else{this.renderV(r,c);}};
sap.suite.ui.commons.TimelineRenderer.renderH=function(r,c){var C=c._outputItem;r.write("<div ");r.writeControlData(c);r.addClass("sapSuiteUiCommonsTimelineH");r.writeStyles();r.writeClasses();r.write(">");r.renderControl(c._headerBar);r.renderControl(c._headerInfoBar);r.write("<div ");r.addClass("sapSuiteUiCommonsTimelineContentsH");r.writeStyles();r.writeClasses();r.write(">");r.write("<div ");r.writeAttribute("id",c.getId()+"-scrollH");r.addClass("sapSuiteUiCommonsTimelineScrollH");r.addStyle("width",11+C.length*18+"rem");r.writeStyles();r.writeClasses();r.write(">");if(C.length>0){for(var i=0;i<C.length;i++){var o=C[i];o._orientation='H';r.renderControl(o);}if(c._showMore){this.renderGetMoreH(r,c);}}else{if(c._finishLoading){r.renderControl(c._emptyList);}}r.write("</div>");r.write("</div>");r.write("</div>");};
sap.suite.ui.commons.TimelineRenderer.renderV=function(r,c){var C=c._outputItem;r.write("<div ");r.writeControlData(c);r.addClass("sapSuiteUiCommonsTimeline");if(c.getWidth()){r.addStyle("width",c.getWidth());}r.writeStyles();r.writeClasses();r.write(">");r.renderControl(c._headerBar);r.renderControl(c._headerInfoBar);r.write("<div ");r.writeAttribute("id",c.getId()+"-content");r.addClass("sapSuiteUiCommonsTimelineContents");if(c.getEnableScroll()){r.addClass("sapSuiteUiCommonsTimelineScrollV");r.addClass("sapSuiteUiCommonsTimelineScroll");}else{r.addClass("sapSuiteUiCommonsTimelineContentsNoScroll");}r.writeClasses();r.write(">");if(c.getEnableScroll()){r.write("<div ");r.writeAttribute("id",c.getId()+"-scroll");r.addClass("sapSuiteUiCommonsTimelineScroll");r.writeStyles();r.writeClasses();r.write(">");}if(C.length>0){for(var i=0;i<C.length;i++){r.renderControl(C[i]);}if(c._showMore){this.renderGetMore(r,c);}}else{if(c._finishLoading){r.renderControl(c._emptyList);}}if(c.getEnableScroll()){r.write("</div>");}r.write("</div>");r.write("</div>");};
sap.suite.ui.commons.TimelineRenderer.renderGetMoreH=function(r,c){r.write("<div ");r.addClass("sapSuiteUiCommonsTimelineGetMoreH");r.writeClasses();r.write(">");r.write("<div ");r.addClass("sapSuiteUiCommonsTimelineGetMoreBarH");r.writeClasses();r.write(">");r.write("</div>");r.write("<div ");r.addClass("sapSuiteUiCommonsTimelineGetMoreBoxH");r.writeClasses();r.write(">");r.renderControl(c._getMoreButton);r.write("</div>");r.write("</div>");};
sap.suite.ui.commons.TimelineRenderer.renderGetMore=function(r,c){r.write("<li ");r.addClass("sapSuiteUiCommonsTimelineGetMore");r.writeClasses();r.write(">");r.write("<div ");r.addClass("sapSuiteUiCommonsTimelineGetMoreBar");r.writeClasses();r.write(">");r.write("</div>");r.write("<div ");r.addClass("sapSuiteUiCommonsTimelineGetMoreBox");r.writeClasses();r.write(">");r.renderControl(c._getMoreButton);r.write("</div>");r.write("</li>");};
